// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sudqzsgamifavcqvputb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN1ZHF6c2dhbWlmYXZjcXZwdXRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk5NDUyNjcsImV4cCI6MjA3NTUyMTI2N30.eOUbramk12uoRH1oCUIjJPmoC5QAa84jVkbrCbY0X60";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});